baseURL = 'http://example.org/'
languageCode = "en-us"
title = "Ati Page"
theme = "hugoProfileReforge"
Paginate = 3
enableRobotsTXT = true

[outputs]
home = [ "HTML", "RSS", "JSON" ]
page = [ "HTML", "RSS" ]

[markup.goldmark.renderer]
unsafe = true

#[[Menus.main]]
#identifier = "blog"
#name = "Blog"
#title = "Blog posts"
#url = "/blogs"
#weight = 1

#[[Menus.main]]
#identifier = "gallery"
#name = "Gallery"
#title = "Blog posts"
#url = "/gallery"
#weight = 2

[params]
title = "Ati Page"
description = "Text about my cool site"
favicon = "/images/fav.png"
useBootstrapCDN = false
animate = true

  [params.font]
  fontSize = "1rem"
  fontWeight = 400
  lineHeight = 1.5
  textAlign = "left"

  [params.navbar]
  align = "ms-auto"
  brandName = "portfolio"
  disableSearch = false

    [params.navbar.menus]
    disableAbout = false
    disableExperience = false
    disableEducation = false
    disableProjects = false
    disableAchievements = false
    disableContact = false

  [params.hero]
  enable = true
  intro = 'สวัสดีครับ Everyone'
  #intro = "Hi, my name is"
  title = "I am Ati Tesakulsiri."
  subtitle = "DSAI master's student"
  content = """I am an undergraduate student at AIT with a DSAI major.
            """
  image = "/images/IMG_7449.JPG"

    [params.hero.bottomImage]
    enable = true

#    [params.hero.button]
 #   enable = true
  #  name = "Github"
   # url = "https://github.com/AtiChetsurakul"
  #  download = false
  #  newPage = true

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-github"
url = "https://github.com/AtiChetsurakul"

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-linkedin"
url = "https://www.linkedin.com/in/ati-tesakulsiri-1a8409263"

#[[params.hero.socialLinks.customIcons]]
#icon = "/fav.png"
#url = "https://example.com"

  [params.about]
  enable = true
  title = "About Me"
  image = "/images/IMG_7449.JPG"
  content = """

  I am an undergraduate student at AIT with a DSAI major. I am interested in Deep learning and
						traditional machine learning, focusing on computer vision tasks. Currently, I am a research
						assistant at AIT-AIcenter for a multi-camera tracking project. Other than vision, I am also
						capable of other tasks, i.e., NLP, prediction models, reinforcement learning, and database
						modeling. I am able to use Docker and Git, create Rest APIs or microservices using PyTorch, and
						implement websites using Flask or Django with Basic CSS and JS. I mainly program in Python.
						Thus, I am also capable of understanding Swift and JS.
"""

    [params.about.skills]
    enable = true
    title = "Here are a few technologies I've been working with recently:"
    mainitem = "https://www.vectorlogo.zone/logos/docker/docker-official.svg"
    items = ["https://www.vectorlogo.zone/logos/pytorch/pytorch-ar21.svg","https://www.vectorlogo.zone/logos/python/python-ar21.svg","https://www.vectorlogo.zone/logos/pocoo_flask/pocoo_flask-ar21.svg","https://www.vectorlogo.zone/logos/grpcio/grpcio-ar21.svg","https://www.vectorlogo.zone/logos/mysql/mysql-ar21.svg","https://www.vectorlogo.zone/logos/heroku/heroku-ar21.svg","https://www.vectorlogo.zone/logos/neo4j/neo4j-ar21.svg","https://www.vectorlogo.zone/logos/plot_ly/plot_ly-ar21.svg","https://www.vectorlogo.zone/logos/gitlab/gitlab-ar21.svg","https://www.vectorlogo.zone/logos/github/github-ar21.svg"]


  [params.experience]
  enable = true

    [[params.experience.items]]
    job = "Research assistant"
    company = "AIT-AIcenter"
    companyUrl = "https://example.com"
    date = "jun 2023 - present"
    content = "I worked as part-time researcher at AIT-AIcenter in multi-camera tracking project (Computer Vison)."



    [[params.experience.items]]
    job = "Scientist Intern (chemist)"
    company = "Forensic police centre 4"
    companyUrl = "https://example.com"
    date = "2020"
    content = "I worked as intern student for Forensic police centre as a chemist."


  [params.education]
  enable = true
  index = false

# 1st School
    [[params.education.items]]
    title = "Master of Science in Data Science and Artificial Intelligence "
    date = "2022 - present"
    GPA = "3.67 / 4.0"
    content = """
After I finish the computer science bootcamp, 
I join this major degree to become a developer who bring 
AI to any device using API or microservices. 
    """
      [params.education.items.school]
      name = "Asian Institute of Technology"
      url = "https://ait.ac.th/"

# 2nd School

    [[params.education.items]]
    title = "Bachelor of Science in Chemistry"
    date = "2017 - 2021"
    GPA = "3.6 / 4.0"
    content = """
At first, I join the university as non-major in science which aim to take the **mathematic major**.
Although I love mathematic, I still get excited when it a time for chemistry lab.
I join the chemistry major in thrid semester and focus in **Analytical chemistry**.

I have a project which got funded from **YSTP, NSTDA**
- In the topic of ` Micro-Solid Phase Extraction and Electrochemical Detection for Serotonin Monitoring`
  - This project invole in the extraction Serotonin from human urine for monitoring with cheap price and highly accurate.

With Analytical chemistry, I have specialize in linear algebra and looking forward for application.
In the end, I saw that this can be applied in to **deep learning** so I shift my interest into computer science

              """

      [params.education.items.school]
      name = "Suranaree University of Technology"
      url = "http://www.sut.ac.th/"

      #[params.education.items.featuredLink]
      #enable = true
      #name = "My academic record"
      #url = "https://example.com"



# To change to certificate

  [params.achievements]
  enable = true

    [[params.achievements.items]]
    title = "CS50"
    content = "I solved all problems with optimal solution."
    url = "https://certificates.cs50.io/3754a2b9-0e35-440f-928b-9ff6959c5992.pdf?size=letter"

    [[params.achievements.items]]
    title = "CS50AI"
    content = "I solved all problems with optimal solution."
    url = "https://certificates.cs50.io/dab00252-47f3-417e-a438-5988f85d8ee1.pdf?size=letter"

    [[params.achievements.items]]
    title = "YSTP scholarship"
    content = "Chemistry project"
    url = "images/certs/YSTP.png"

# Project

  [params.projects]
  enable = true

    [[params.projects.items]]
    title = "NLP application"
    content = "build a Flask web application which serving various Deep learning NLP model for tasks"
    image = "/images/projects/nlpapp3.png"
    badges = [ "NLP","pytorch","Hugging Face" ]

      [params.projects.items.featured]
      name = "Demo"
      link = "https://github.com/AtiChetsurakul/NLP_AppPresentation"

      [[params.projects.items.links]]
      icon = "fab fa-github"
      url = "https://github.com/AtiChetsurakul/NLP_AppPresentation"


  # PROJECT 2
    [[params.projects.items]]
    title = "Bros of Rainbow"
    content = "Using RAINBOW, a varient of Deep Q-learning, to train an agent for super mario playing"
    image = "/images/projects/rainbros2.gif"
    badges = [ "reinforcement learning","pytorch","gym" ]

      [params.projects.items.featured]
      name = "Read"
      link = "https://github.com/AtiChetsurakul/BrosOfRainbow/blob/main/Mario_Rainbow__DRL_.pdf"

      [[params.projects.items.links]]
      icon = "fab fa-github"
      url = "https://github.com/AtiChetsurakul/BrosOfRainbow"

# PROJECT 3
    [[params.projects.items]]
    title = "Computer Vision project"
    content = "Currently private."
    image = "/images/projects/pic.png"
    badges = [ ]

      [params.projects.items.featured]
      name = "--"
      link = ""

      #[[params.projects.items.links]]
      #icon = "fab fa-github"
      #url = ""



    [[params.projects.items]]
    title = "Serotonin Extraction"
    content = "Micro-Solid Phase Extraction and Electrochemical Detection for Serotonin Monitoring. Funded by YSTP, NSTDA"
    image = "/images/projects/serotonin.png"
    badges = [ "SPE", "HPLC", "Chemistry" ]
      [params.projects.items.featured]
      name = "Demo"
      link = "https://drive.google.com/file/d/13QOegKGa2QXYjpA4xXpY2xOexwyF_7Yy/view?usp=sharing"

      [[params.projects.items.links]]
      icon = "fa fa-envelope"
      url = "mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f"

      [[params.projects.items.links]]
      icon = "fas fa-certificate"
      url = "images/certs/YSTP.png"


# PROJECT 2
    [[params.projects.items]]
    title = "Chemlab Copilot"
    content = "A Basic IOS application built to send an API requests to fetch chemical data."
    image = "/images/projects/chemlabReal.png"
    badges = [ "Swift","Story board","Xcode" ]

      [params.projects.items.featured]
      name = "Demo"
      link = ""

      [[params.projects.items.links]]
      icon = "fab fa-github"
      url = ""

  # PROJECT 3
    [[params.projects.items]]
    title = "Diabete classification using Raman spectrums"
    content = "Using scikit learn and classic ML tool to classify the patient."
    image = "/images/projects/ramanR.png"
    badges = [ "Python","sklearn" ]

      [params.projects.items.featured]
      name = "PP"
      link = "https://github.com/AtiChetsurakul/DataScienceAndMLProjects/blob/main/Diabete_detection_withRamanSpec/CP%20presentation%20.pdf"

      [[params.projects.items.links]]
      icon = "fab fa-github"
      url = "https://github.com/AtiChetsurakul/DataScienceAndMLProjects/blob/main/Diabete_detection_withRamanSpec"


  # PROJECT 7
    [[params.projects.items]]
    title = "Joules of Saim"
    content = "A web application intregrated with interactive dasboard for electricities prediction"
    image = "/images/projects/jouleofs.png"
    badges = [ "Flask","Dash" ]

      [params.projects.items.featured]
      name = "Demo"
      link = "http://st123009.pythonanywhere.com/"

      [[params.projects.items.links]]
      icon = "fab fa-github"
      url = "https://github.com/TonsonP/Joules_of_Siam"

  # PROJECT 8
    [[params.projects.items]]
    title = "Secret NLP project"
    content = "To be anouce"
    image = "/images/projects/pic.png"
    badges = [ "--","--" ]

      [params.projects.items.featured]
      name = "--"
      link = ""

      [[params.projects.items.links]]
      icon = "fab fa-github"
      url = ""

  # PROJECT 9
    [[params.projects.items]]
    title = "Secret CV project"
    content = "TO be anouce"
    image = "/images/projects/pic.png"
    badges = [ "--","--" ]

      [params.projects.items.featured]
      name = "--"
      link = ""

      [[params.projects.items.links]]
      icon = "fab fa-github"
      url = ""


# Contact
  [params.contact]
  enable = true
  content = "If you interest, please contact me."
  email = "ksde34@gmail.com"
  btnName = "email"


# About this site


[params.footer.socialNetworks]
github = "https://github.com/AtiChetsurakul"
linkedin = "https://www.linkedin.com/in/ati-tesakulsiri-1a8409263"


  [params.listPages]
  disableFeaturedImage = false

[params.singlePages.readTime]
enable = true
content = "min read"

[params.singlePages.scrollprogress]
enable = true

  [params.terms]
  read = "Read"
  toc = "Table Of Contents"
  copyright = "All rights reserved"
  pageNotFound = "Page not found"
  emailText = "Check out this site"

#  [params.datesFormat]
#  article = "Jan 2, 2006"
#  articleList = "Jan 2, 2006"
#  articleRecent = "Jan 2, 2006"

