baseURL = 'http://example.org/'
languageCode = "en-us"
title = "Ati Page"
theme = "hugoProfileReforge"
Paginate = 3
enableRobotsTXT = true

[outputs]
home = [ "HTML", "RSS", "JSON" ]
page = [ "HTML", "RSS" ]

[markup.goldmark.renderer]
unsafe = true

#[[Menus.main]]
#identifier = "blog"
#name = "Blog"
#title = "Blog posts"
#url = "/blogs"
#weight = 1

#[[Menus.main]]
#identifier = "gallery"
#name = "Gallery"
#title = "Blog posts"
#url = "/gallery"
#weight = 2

[params]
title = "Ati Page"
description = "Text about my cool site"
favicon = "/images/faceimg.png"
useBootstrapCDN = false
animate = true

  [params.font]
  fontSize = "1rem"
  fontWeight = 400
  lineHeight = 1.5
  textAlign = "left"

  [params.navbar]
  align = "ms-auto"
  brandName = "portfolio"
  disableSearch = false

    [params.navbar.menus]
    disableAbout = false
    disableExperience = false
    disableEducation = false
    disableProjects = false
    disableAchievements = false
    disableContact = false

  [params.hero]
  enable = true
  #intro = "Hi, my name is"
  title = "Ati Tesakulsiri."
  subtitle = "I am DSAI master's student"
  content = "I am an undergraduate student at AIT with a DSAI major."
  image = "/images/faceimg.png"

    [params.hero.bottomImage]
    enable = true

#    [params.hero.button]
 #   enable = true
  #  name = "Github"
   # url = "https://github.com/AtiChetsurakul"
  #  download = false
  #  newPage = true

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-github"
url = "https://github.com/AtiChetsurakul"

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-linkedin"
url = "https://example.com"

#[[params.hero.socialLinks.customIcons]]
#icon = "/fav.png"
#url = "https://example.com"

  [params.about]
  enable = true
  title = "About Me"
  image = "/images/faceimg.png"
  content = """

  I am an undergraduate student at AIT with a DSAI major. I am interested in Deep learning and
						traditional machine learning, focusing on computer vision tasks. Currently, I am a research
						assistant at AIT-AIcenter for a multi-camera tracking project. Other than vision, I am also
						capable of other tasks, i.e., NLP, prediction models, reinforcement learning, and database
						modeling. I am able to use Docker and Git, create Rest APIs or microservices using PyTorch, and
						implement websites using Flask or Django with Basic CSS and JS. I mainly program in Python.
						Thus, I am also capable of understanding Swift and JS.
"""

    [params.about.skills]
    enable = true
    title = "Here are a few technologies I've been working with recently:"
    mainitem = "https://www.vectorlogo.zone/logos/docker/docker-official.svg"
    items = ["https://www.vectorlogo.zone/logos/pytorch/pytorch-ar21.svg","https://www.vectorlogo.zone/logos/python/python-ar21.svg","https://www.vectorlogo.zone/logos/pocoo_flask/pocoo_flask-ar21.svg","https://www.vectorlogo.zone/logos/grpcio/grpcio-ar21.svg","https://www.vectorlogo.zone/logos/mysql/mysql-ar21.svg","https://www.vectorlogo.zone/logos/heroku/heroku-ar21.svg","https://www.vectorlogo.zone/logos/neo4j/neo4j-ar21.svg","https://www.vectorlogo.zone/logos/plot_ly/plot_ly-ar21.svg","https://www.vectorlogo.zone/logos/gitlab/gitlab-ar21.svg","https://www.vectorlogo.zone/logos/github/github-ar21.svg"]


  [params.experience]
  enable = true

    [[params.experience.items]]
    job = "Research assistant"
    company = "AIT-AIcenter"
    companyUrl = "https://example.com"
    date = "jun 2022 - present"
    content = "I worked as part-time researcher at AIT-AIcenter in multi-camera tracking project (Computer Vison)."



    [[params.experience.items]]
    job = "Scientist Intern (chemist)"
    company = "Forensic police centre 4"
    companyUrl = "https://example.com"
    date = "2020"
    content = "I worked as intern student for Forensic police centre as a chemist."


  [params.education]
  enable = true
  index = false


    [[params.education.items]]
    title = "Master of Science in Data Science and Artificial Intelligence "
    date = "2022 - present"
    GPA = "3.67 / 4.0"
    content = """
    After I finish the computer science bootcamp, I join this major
    since I love computer science, and It is quite related to my previuos degree.
"""

      [params.education.items.school]
      name = "Asian Institute of Technology"
      url = "https://ait.ac.th/"


    [[params.education.items]]
    title = "Bachelor of Science in Chemistry"
    date = "2017 - 2021"
    GPA = "3.6 / 4.0"
    content = """
To add
"""

      [params.education.items.school]
      name = "Suranaree University of Technology"
      url = "http://www.sut.ac.th/"

      [params.education.items.featuredLink]
      enable = true
      name = "My academic record"
      url = "https://example.com"


  [params.achievements]
  enable = true

    [[params.achievements.items]]
    title = "CS50 varients"
    content = "I solved all problems with optimal solution."
    url = "https://example.com"


  [params.projects]
  enable = true

    [[params.projects.items]]
    title = "Hugo Profile"
    content = "A highly customizable and mobile first Hugo template for personal portfolio and blog."
    image = "/images/projects/profile.png"
    badges = [ "Hugo", "Bootstrap", "Javascript" ]

      [params.projects.items.featured]
      name = "Demo"
      link = "https://hugo-profile.netlify.app"

      [[params.projects.items.links]]
      icon = "fa fa-envelope"
      url = "mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f"

      [[params.projects.items.links]]
      icon = "fab fa-github"
      url = "https://github.com/gurusabarish/hugo-profile"

      [[params.projects.items.links]]
      icon = "fab fa-twitter"
      url = "https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile"

    [[params.projects.items]]
    title = "Image Converter"
    content = "A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django."
    image = "/images/projects/converter.jpg"
    badges = [ "Django", "Bootstrap" ]

      [params.projects.items.featured]
      name = "Demo"
      link = "https://django-converter.herokuapp.com"

      [[params.projects.items.links]]
      icon = "fab fa-github"
      url = "https://github.com/gurusabarish/converter"

    [[params.projects.items]]
    title = "Hugo Profile V2"
    content = "A clean and simple Hugo template for personal portfolio and blog."
    image = "/images/projects/profile2.jpg"
    badges = [ "Hugo", "Bootstrap", "Javascript" ]

      [params.projects.items.featured]
      name = "Demo V2"
      link = "https://hugo-profile-2.netlify.app"

      [[params.projects.items.links]]
      icon = "fab fa-github"
      url = "https://github.com/gurusabarish/HugoProfileV2"

  [params.contact]
  enable = true
  content = "If you interest, please contact me."
  email = "ksde34@gmail.com"
  btnName = "Mail me"


[params.footer.socialNetworks]
github = "https://github.com"
linkedin = "https://linkedin.com"


  [params.listPages]
  disableFeaturedImage = false

[params.singlePages.readTime]
enable = true
content = "min read"

[params.singlePages.scrollprogress]
enable = true

  [params.terms]
  read = "Read"
  toc = "Table Of Contents"
  copyright = "All rights reserved"
  pageNotFound = "Page not found"
  emailText = "Check out this site"

#  [params.datesFormat]
#  article = "Jan 2, 2006"
#  articleList = "Jan 2, 2006"
#  articleRecent = "Jan 2, 2006"

